### ISSUE TITLE
Crash on some inputs

### ISSUE THREAD

**Issue by kovzol** [PetterS/qepcad#3]
The following input results in a segmentation fault on Linux 64 bit:
```
[]
(m,b,c)
1
(Eb)(Ec)[m>0 /\ 1+b>c /\ b+c>1 /\ c+1>b /\ 4 b^3+4 b^2 c+4 b^2+4 b c^2+4 b+4 c^3+4 c^2+4 c+4=(b^3 m+3 b^2 c m+3 b^2 m+3 b c^2 m+14 b c m+3 b m+c^3 m+3 c^2 m+3 c m+m)].
assume[m>0].
finish
```
The original version of QEPCAD returns the correct result.

**Comment by PetterS** [comment]
Thanks for the report. Perhaps I can find some time to investigate this.

**Comment by PetterS** [comment]
I get

> An equivalent quantifier-free formula:
>
> m - 2 < 0 /\ 35 m - 36 >= 0

With
> gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904

**Comment by kovzol** [comment]
Thanks for checking! I have
> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
on an Ubuntu 16.04.3 (64 bit, 16 GB RAM), and
> gcc (Debian 4.9.2-10) 4.9.2
on a Debian 8 (64 bit, 8 GB RAM). Both servers are heavily used by other tasks as well, thus the available RAM may be much less. I'll try another build on a third system as well (that has more resources).

**Comment by kovzol** [comment]
It indeed works nicely on a different system (Ubuntu 17.04, gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406, 8 GB RAM, 64 bit). Maybe there is an issue in gcc?

**Comment by kovzol** [comment]
Another positive result: Linux Mint 18.2 Sonya, gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 9 GB RAM, 64 bit. It works.
